
services:

  db-service:
    build: ../db
    ports:
      - "5433:5432"
    env_file:
      - ../db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  auth-service:
    build: ../backend/auth-service
    ports:
      - "5001:5001"
    env_file:
      - ../backend/auth-service/.env

  user-service:
    build: ../backend/user-service
    ports:
      - "5002:5002"
    env_file:
      - ../backend/user-service/.env

  institution-service:
    build: ../backend/institution-service
    ports:
      - "5003:5003"
    env_file:
      - ../backend/institution-service/.env
    depends_on:
      - db-service


volumes:
  postgres_data:
