
services:

  db-service:
    build: ./db-service
    ports:
      - "5433:5432"
    env_file:
      - ./db-service/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-service/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./db-service/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    restart: always

  auth-service:
    build: ../backend/auth-service
    ports:
      - "5001:5001"
    env_file:
      - ../backend/auth-service/.env

  user-service:
    build: ../backend/user-service
    ports:
      - "5002:5002"
    env_file:
      - ../backend/user-service/.env

  institution-service:
    build: ../backend/institution-service
    ports:
      - "5003:5003"
    env_file:
      - ../backend/institution-service/.env
    depends_on:
      - db-service
  
  grades-service:
    build: ../backend/grades-service
    ports:
      - "5004:5004"
    env_file:
      - ../backend/grades-service/.env
    depends_on:
      - db-service

  course-service:
      build: ../backend/course-service
      ports:
        - "5005:5005"
      env_file:
        - ../backend/course-service/.env
      depends_on:
        - db-service
        
  review-service:
    build: ../backend/review-service
    ports:
      - "5006:5006"
    env_file:
      - ../backend/review-service/.env
    depends_on:
      - db-service

  statistics-service:
    build: ../backend/statistics-service
    ports:
      - "5007:5007"
    env_file:
      - ../backend/statistics-service/.env
    depends_on:
      - db-service  

  credits-service:
    build: ../backend/credits-service
    ports:
      - "5008:5008"
    env_file:
      - ../backend/credits-service/.env
    depends_on:
      - db-service

  upload-service:
    build: ../backend/upload-service
    ports:
      - "5009:5009"
    env_file:
      - ../backend/upload-service/.env
      
volumes:
  postgres_data:
