version: '3.9'
services:

  auth-service:
    build: ../backend/auth-service
    ports:
      - "5001:5001"
    env_file:
      - ../backend/auth-service/.env

  user-service:
    build: ../backend/user-service
    ports:
      - "5002:5002"
    env_file:
      - ../backend/user-service/.env

