
services:

  frontend:
    build: ../frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"

  db-service:
    build: ../backend/db-service
    ports:
      - "5433:5432"
    env_file:
      - ../backend/db-service/.env
    volumes:
      - ../backend/db-service/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ../backend/db-service/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

    restart: always

  auth-service:
    build: ../backend/auth-service
    ports:
      - "5001:5001"
    env_file:
      - ../backend/auth-service/.env
    depends_on:
      - auth-db

  auth-db:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: secret
    volumes:
      - ../backend/auth-service/init/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../backend/auth-service/init/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

  user-service:
    build: ../backend/user-service
    ports:
      - "5002:5002"
    env_file:
      - ../backend/user-service/.env
    depends_on:
      - user-db

  user-db:
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: useruser
      POSTGRES_PASSWORD: secret
    volumes:
      - ../backend/user-service/init/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../backend/user-service/init/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql


  institution-service:
    build: ../backend/institution-service
    ports:
      - "5003:5003"
    env_file:
      - ../backend/institution-service/.env
    depends_on:
      - db-service
  
  grades-service:
    build: ../backend/grades-service
    ports:
      - "5004:5004"
    env_file:
      - ../backend/grades-service/.env
    depends_on:
      - grades-db

  grades-db:
    image: postgres:16
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: gradedb
      POSTGRES_USER: gradeuser
      POSTGRES_PASSWORD: secret
    volumes:
      - ../backend/grades-service/init/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../backend/grades-service/init/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql


  course-service:
    build: ../backend/course-service
    ports:
      - "5005:5005"
    env_file:
      - ../backend/course-service/.env
    depends_on:
      - course-db
      
  course-db:
    image: postgres:16
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: clearsky
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../backend/course-service/init/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../backend/course-service/init/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

        
  review-service:
    build: ../backend/review-service
    ports:
      - "5006:5006"
    env_file:
      - ../backend/review-service/.env
    depends_on:
      - db-service

  statistics-service:
    build: ../backend/statistics-service
    ports:
      - "5007:5007"
    env_file:
      - ../backend/statistics-service/.env
    depends_on:
      - db-service  

  credits-service:
    build: ../backend/credits-service
    ports:
      - "5008:5008"
    env_file:
      - ../backend/credits-service/.env
    depends_on:
      - db-service

  upload-service:
    build: ../backend/upload-service
    ports:
      - "5009:5009"
    env_file:
      - ../backend/upload-service/.env

      
volumes:
  postgres_data:
